WebBanHangOnline/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using WebBanHangOnline.Data;

namespace WebBanHangOnline.Controllers
{
    public class MenuController : Controller
    {
        private readonly ApplicationDbContext _db;
        public MenuController(ApplicationDbContext db)
        {
            _db = db;
        }
        [Route("menu")]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult MenuTop()
        {
            var items = _db.Categories.OrderBy(x=>x.Position).ToList();
            return PartialView("_MenuTop", items);
        }
        public IActionResult MenuProductCategory()
        {
            var items = _db.ProductCategories.ToList();
            return PartialView("_MenuProductCategory", items);
        }
        public IActionResult MenuLeft(int? id)
        {
            if(id != null)
			{
                ViewBag.CateId = id;

            }
            var items = _db.ProductCategories.ToList();
            return PartialView("_MenuLeft", items);
        }
        public IActionResult MenuArrivals()
        {
            var items = _db.ProductCategories.ToList();
            return PartialView("_MenuArrivals", items);
        }
    }
}

WebBanHangOnline/ViewComponents/MenuTopViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebBanHangOnline.Data;
namespace WebBanHangOnline.ViewComponents
{
    public class MenuTopViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _db;

        public MenuTopViewComponent(ApplicationDbContext db)
        {
            _db = db;
        }

        public IViewComponentResult Invoke()
        {
            var items = _db.Categories.OrderBy(x => x.Position).ToList();
            return View("_MenuTop", items);
        }
    }
}

WebBanHangOnline/ViewComponents/Partial_SubcribeViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebBanHangOnline.ViewComponents
{
    public class Partial_SubcribeViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            
            return View("Partial_Subcribe");
        }
    }
}

WebBanHangOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @*<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebBanHangOnline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebBanHangOnline.styles.css" asp-append-version="true" />*@
	<title>Colo Shop</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Colo Shop Template">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="~/assets/styles/bootstrap4/bootstrap.min.css">
	<link href="~/assets/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="~/assets/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
	<link rel="stylesheet" type="text/css" href="~/assets/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
	<link rel="stylesheet" type="text/css" href="~/assets/plugins/OwlCarousel2-2.2.1/animate.css">
@*	<link rel="stylesheet" type="text/css" href="~/assets/styles/main_styles.css">*@
	<link rel="stylesheet" type="text/css" href="~/assets/styles/responsive.css">
	<link rel="stylesheet" type="text/css" href="~/assets/plugins/jquery-ui-1.12.1.custom/jquery-ui.css">
</head>
<body>
    <div class="super_container">

	<!-- Header -->

	<header class="header trans_300">

		<!-- Top Navigation -->

		<div class="top_nav">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						<div class="top_nav_left">free shipping on all u.s orders over $50</div>
					</div>
					<div class="col-md-6 text-right">
						<div class="top_nav_right">
							<ul class="top_nav_menu">

								<!-- Currency / Language / My Account -->

								<li class="currency">
									<a href="#">
										usd
										<i class="fa fa-angle-down"></i>
									</a>
									<ul class="currency_selection">
										<li><a href="#">cad</a></li>
										<li><a href="#">aud</a></li>
										<li><a href="#">eur</a></li>
										<li><a href="#">gbp</a></li>
									</ul>
								</li>
								<li class="language">
									<a href="#">
										English
										<i class="fa fa-angle-down"></i>
									</a>
									<ul class="language_selection">
										<li><a href="#">French</a></li>
										<li><a href="#">Italian</a></li>
										<li><a href="#">German</a></li>
										<li><a href="#">Spanish</a></li>
									</ul>
								</li>
								<li class="account">
									
									@if(!User.Identity.IsAuthenticated){
											<a href="#">
										My Account
										<i class="fa fa-angle-down"></i>
									</a>
											<ul class="account_selection">
										<li><a href="/account/login"><i class="fa fa-sign-in" aria-hidden="true"></i>Sign In</a></li>
										<li><a href="/account/register"><i class="fa fa-user-plus" aria-hidden="true"></i>Register</a></li>
									</ul>
										}
										else
										{
											<a href="#">
										Welcome: @User.Identity.Name
										<i class="fa fa-angle-down"></i>
									</a>
											<ul class="account_selection" style="width:max-content">
										<li><a href="/account/profile"><i class="fa fa-user" aria-hidden="true"></i>Profile</a></li>
										<li><a href="/account/like"><i class="fa fa-user" aria-hidden="true"></i>Sản phẩm yêu thích</a></li>
										<li><a href="javascript:document.getElementById('logOffForm').submit()"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a></li>
									</ul>
										}
									</li>
							</ul>
							@if(User.Identity.IsAuthenticated){
    <div style="display:none">
        <form id="logOffForm" action="@Url.Action("LogOff", "Account")" method="post">
            @Html.AntiForgeryToken()
        </form>
    </div>
}
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Main Navigation -->

		<div class="main_nav_container">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 text-right">
						<div class="logo_container">
							<a href="/">colo<span>shop</span></a>
						</div>
						<nav class="navbar">
							@*@Html.Action("MenuTop", "Menu")*@
							@await Component.InvokeAsync("MenuTop")
							<ul class="navbar_user">
								<li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-user" aria-hidden="true"></i></a></li>
								<li class="checkout">
										@if (!User.Identity.IsAuthenticated)
										{
											<a href="/account/login">
												<i class="fa fa-shopping-cart" aria-hidden="true"></i>
												<span id="checkout_items" class="checkout_items">0</span>
											</a>
										}
										else
										{
											<a href="/gio-hang">
												<i class="fa fa-shopping-cart" aria-hidden="true"></i>
												<span id="checkout_items" class="checkout_items">0</span>
											</a>
										}

								</li>
							</ul>
							<div class="hamburger_container">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>
						</nav>
					</div>
				</div>
			</div>
		</div>

	</header>

	<div class="fs_menu_overlay"></div>
	<div class="hamburger_menu">
		<div class="hamburger_close"><i class="fa fa-times" aria-hidden="true"></i></div>
		<div class="hamburger_menu_content text-right">
			<ul class="menu_top_nav">
				<li class="menu_item has-children">
					<a href="#">
						usd
						<i class="fa fa-angle-down"></i>
					</a>
					<ul class="menu_selection">
						<li><a href="#">cad</a></li>
						<li><a href="#">aud</a></li>
						<li><a href="#">eur</a></li>
						<li><a href="#">gbp</a></li>
					</ul>
				</li>
				<li class="menu_item has-children">
					<a href="#">
						English
						<i class="fa fa-angle-down"></i>
					</a>
					<ul class="menu_selection">
						<li><a href="#">French</a></li>
						<li><a href="#">Italian</a></li>
						<li><a href="#">German</a></li>
						<li><a href="#">Spanish</a></li>
					</ul>
				</li>
				<li class="menu_item has-children">
					<a href="#">
						My Account
						<i class="fa fa-angle-down"></i>
					</a>
					<ul class="menu_selection">
						<li><a href="#"><i class="fa fa-sign-in" aria-hidden="true"></i>Sign In</a></li>
						<li><a href="#"><i class="fa fa-user-plus" aria-hidden="true"></i>Register</a></li>
					</ul>
				</li>
				<li class="menu_item"><a href="#">home</a></li>
				<li class="menu_item"><a href="#">shop</a></li>
				<li class="menu_item"><a href="#">promotion</a></li>
				<li class="menu_item"><a href="#">pages</a></li>
				<li class="menu_item"><a href="#">blog</a></li>
				<li class="menu_item"><a href="#">contact</a></li>
			</ul>
		</div>
	</div>

	<!-- Slider -->

	@RenderBody()

	

	<!-- Newsletter -->

	@*@await Component.InvokeAsync("Partial_Subcribe")*@
	@*@Html.Partial("Partial_Subcribe")*@

	<!-- Footer -->

	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
						<ul class="footer_nav">
							<li><a href="#">Blog</a></li>
							<li><a href="#">FAQs</a></li>
							<li><a href="contact.html">Contact us</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
						<ul>
							<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<div class="footer_nav_container">
						<div class="cr">©2018 All Rights Reserverd. Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#">Colorlib</a> &amp; distributed by <a href="https://themewagon.com">ThemeWagon</a></div>
					</div>
				</div>
			</div>
		</div>
	</footer>

</div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@

    <script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/assets/js/jquery-3.2.1.min.js"></script>
	<script src="~/assets/styles/bootstrap4/popper.js"></script>
	<script src="~/assets/styles/bootstrap4/bootstrap.min.js"></script>
	<script src="~/assets/plugins/Isotope/isotope.pkgd.min.js"></script>
	<script src="~/assets/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
	<script src="~/assets/plugins/easing/easing.js"></script>
	<script src="~/assets/js/custom.js"></script>
	<script src="~/assets/plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
	<script src="~/js/jsShopping1.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebBanHangOnline/Views/Shared/_LayoutForgotPass.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="~/LayoutAdmin/plugins/fontawesome-free/css/all.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="~/LayoutAdmin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/LayoutAdmin/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    @RenderBody()
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="~/LayoutAdmin/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/LayoutAdmin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="~/LayoutAdmin/dist/js/adminlte.min.js"></script>
</body>
</html>

WebBanHangOnline/Views/Shared/_LayoutRegister.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Registration Page</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="~/LayoutAdmin/plugins/fontawesome-free/css/all.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="~/LayoutAdmin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/LayoutAdmin/dist/css/adminlte.min.css">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>

  <div class="card">
    @RenderBody()
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="~/LayoutAdmin/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/LayoutAdmin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="~/LayoutAdmin/dist/js/adminlte.min.js"></script>
</body>
</html>